name: Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to release from"
        required: true
        default: "master"

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      release-version: ${{ steps.semantic.outputs.release-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Semantic release
        id: semantic
        uses: codfish/semantic-release-action@v3
        env:
          GH_TOKEN: ${{ secrets.GIT_PACKAGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: release
    if: needs.release.outputs.new-release-published == 'true'
    runs-on: [self-hosted, Standard]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ needs.release.inputs.branch }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: Set version
        run: npm version --no-git-tag-version ${{ needs.release.outputs.release-version }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
