name: Release
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to release from"
        required: true
        default: "master"

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      release-version: ${{ steps.semantic.outputs.release-version }}
      release-notes: ${{ steps.semantic.outputs.release-notes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Semantic release
        id: semantic
        uses: codfish/semantic-release-action@v3
        with:
          branches: ${{ github.event.inputs.branch }}
        env:
          GH_TOKEN: ${{ secrets.GIT_PACKAGE_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  microft-teams:
    name: Post to Microsoft Teams
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Post to Microsoft Teams
        if: needs.release.outputs.new-release-published == 'true'
        run: |
          curl -H "Content-Type: application/json" -d '{
          "@type": "MessageCard",
          "@context": "http://schema.org/extensions",
          "summary": "New Release Published",
          "sections": [{
            "text": "Design system release v${{ needs.release.outputs.release-version }}
            \n\n${{ needs.release.outputs.release-notes }}"}]}' ${{ secrets.TEAMS_WEBHOOK_URI }}
  publish:
    needs: release
    if: needs.release.outputs.new-release-published == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - name: Ensure clean working directory
        run: git reset --hard && git clean -fdx
      - name: update version
        run: npm version ${{ needs.release.outputs.release-version }}
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGE_TOKEN }}
